name: Deploy to VPS

on:
  push:
    branches:
      - main  # Jalankan ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/repo
            git pull origin main
            npm install
            npx drizzle-kit push
            pm2 restart server || pm2 start dist/server.js --name "server"
